feat(cngfw): Introduce CNGFW vnet module and example
PaloAltoNetworks/terraform-azurerm-swfw-modules pull request #113
Opened 2024-12-16 13:29 UTC by stefanskid

## Description

Introduce CNGFW vnet module and example
## Motivation and Context
#28

## How Has This Been Tested?
The module and example was tested in local lab environment

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

2025-02-19 08:46 UTC, migara commented
/idempotence paths="examples/common_cloudngfw" tf_version="1.7 1.8"

2025-02-24 13:25 UTC, acelebanski commented on modules/cngfw/variables.tf
> +        can(regex("^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$", nat.backend_ip
This regex is very complex and difficult to read. In other modules we used `"^(\\d{1,3}\\.){3}\\d{1,3}$"`. Perhaps it's enough?

2025-02-24 13:28 UTC, acelebanski commented on modules/cngfw/variables.tf
> +                                        Resource. This field is required when `management_mode` is set to "rulestack".
In variable descriptions use those single quotes instead of double (on keyword **rulestack**) in order to highlight this in the README.

2025-03-04 13:33 UTC, acelebanski requested changes
Some more comments from my end. Keep up the good work! 💯

2025-03-04 13:33 UTC, acelebanski commented on modules/cloudngfw/main.tf
> +    public_ip_address_ids = (var.public_ip_ids != null ? values(var.public_ip_ids) :
Will this property even accept an empty list if it's required? I'd rather do something like this:
```hcl
public_ip_address_ids = coalesce(
  try(values(var.public_ip_ids), null),
  try([azurerm_public_ip.this[0].id], [data.azurerm_public_ip.this[0].id], null)
)
```
If none of the 3 options is provided, the `coalesce` function will fail.

2025-03-04 13:33 UTC, acelebanski commented on modules/cloudngfw/main.tf
> +    egress_nat_ip_address_ids = (var.egress_nat_ip_ids != null ? values(var.egress_nat_ip_ids) :
Similarly to `public_ip_address_ids` property.

2025-03-04 13:33 UTC, acelebanski commented on modules/cloudngfw/variables.tf
> +variable "public_ip_ids" {
Any reason why this variable is standalone now instead of being under `cngfw_config` like other public ip related options?

2025-03-04 13:33 UTC, acelebanski commented on modules/cloudngfw/variables.tf
> +variable "egress_nat_ip_ids" {
Same question as in regards to `public_ip_ids`.

2025-03-04 13:33 UTC, acelebanski commented on modules/cloudngfw/variables.tf
> +variable "palo_alto_virtual_appliance_name" {
Can't we just reuse the `var.name` for that? Seems a little bit confusing.

2025-03-04 13:33 UTC, acelebanski commented on modules/cloudngfw/variables.tf
> +  validation { #destination_nat_protocol
Don't forget spaces after `#`.

2025-03-04 13:33 UTC, acelebanski commented on modules/cloudngfw/variables.tf
> +  - `palo_alto_virtual_appliance_key` - (`string`, optional) the key referencing a Palo Alto Virtual Appliance, if applicable.
This property isn't a thing anymore, is it?

2025-03-04 13:33 UTC, acelebanski commented on modules/cloudngfw/variables.tf
> +  The former plan_id panw-cloud-ngfw-payg is defined as stop sell, but has been set as the default to not break any existing
Put those plan & offer names in single quotes (code).

2025-03-04 13:33 UTC, acelebanski commented on modules/cloudngfw/variables.tf
> +    error_message = "The `destination_nat_name` property value has to be unique in a particular destination_nat."
In every module, we put `error_message` inside `EOF` block, regardless of the length of the message.

Regarding the quotes, see this reference from another module:
```hcl
The `identity_type` property can be one of \"SystemAssigned\", \"UserAssigned\" or \"SystemAssigned, UserAssigned\".
```

2025-03-04 15:39 UTC, stefanskid commented on modules/cloudngfw/variables.tf
> +variable "public_ip_ids" {
By defining public_ip_ids separately, it can be sourced from another module (like public_ip) or manually assigned, making the configuration more flexible.

2025-03-04 15:39 UTC, stefanskid commented on modules/cloudngfw/variables.tf
> +variable "egress_nat_ip_ids" {
By defining egress_nat_ip_ids separately, it can be sourced from another module (like public_ip) or manually assigned, making the configuration more flexible.

2025-03-04 15:47 UTC, acelebanski commented on modules/cloudngfw/variables.tf
> +variable "public_ip_ids" {
@stefanskid how? In the module you'd just reference this variable by `var.cngfw_config.public_ip_ids` instead of `var.public_ip_ids`. In the gluecode you'd just merge `public_ip` module output with the `cngfw_config` map.

2025-03-05 13:47 UTC, acelebanski commented on examples/common_cloudngfw/example.tfvars
> +public_ips = {
We don't use `public_ip` module in the examples (it's in the gluecode and variables but not in tfvars), go with PIP generation within the `cloudngfw` module instead.

2025-03-07 13:31 UTC, pavelrn commented
@acelebanski The delegation needs to include `actions` like the one below. Otherwise it doesn't converge in my case.

```
dynamic "delegation" {
    for_each = each.value.enable_cloudngfw_delegation ? [1] : []
    content {
      name = "cloudngfw_delegation"
      service_delegation {
        name = "PaloAltoNetworks.Cloudngfw/firewalls"
        actions = [
          "Microsoft.Network/virtualNetworks/subnets/join/action"
        ]
      }
    }
  }
```

2025-03-11 14:33 UTC, alperenkose commented on examples/common_cloudngfw/example.tfvars
> +        network_security_group_key  = "cloudngfw-dnat"
Let's create an NSG as per ref arch for Private subnet.

2025-03-12 15:28 UTC, acelebanski commented on examples/common_cloudngfw/example.tfvars
> +public_ips = {
Changed.

2025-03-12 15:34 UTC, acelebanski commented
/idempotence paths="examples/common_cloudngfw" tf_version="1.5 1.6 1.7 1.8"

2025-03-12 20:02 UTC, acelebanski approved these changes
Looking all good now! 👍

2025-03-12 20:02 UTC, merged